config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  get '/auth/github/callback', to: 'sessions#create'
  get '/dashboard', to: 'dashboard#show'
  get '/public', to: 'repos#public_repos'
  get '/private', to: 'repos#private_repos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def public_repos
    response = GithubService.get_public_repos(current_user)
    @repos = JSON.parse(response.body, symbolize_names: true)
  end

  def private_repos
    response = GithubService.get_private_repos(current_user)
    @repos = JSON.parse(response.body, symbolize_names: true)
  end
end

app/controllers/sessions_controller.rb
class SessionsController <  ApplicationController
  def create
    response = OauthService.get_access_token(params[:code])

    data = JSON.parse(response.body, symbolize_names: true)
    access_token = data[:access_token]

    response = OauthService.get_user(access_token)
    data = JSON.parse(response.body, symbolize_names: true)

    user          = User.find_or_create_by(uid: data[:id])
    user.username = data[:login]
    user.uid      = data[:id]
    user.token    = access_token
    user.save

    session[:user_id] = user.id

    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<h1>Welcome, <%= current_user.username %></h1>

<%= link_to "Public Repo's", public_path %><br>
<%= link_to "Private Repo's", private_path %>

app/views/home/index.html.erb
<h1>Welcome!</h1>
<%= link_to "Login", "https://github.com/login/oauth/authorize?client_id=2901152965a92c3b41d2&scope=repo" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OauthWorkshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repos/private_repos.html.erb
<h1><%= current_user.username %>'s private repository list</h1>

<h3>Repository count <%= @repos.count %></h3>
<% @repos.each do |repo| %>
  <% if repo[:private] == true %>
    <%= link_to repo[:name], repo[:html_url] %><br><br>
  <% end %>
<% end %>

app/views/repos/public_repos.html.erb
<h1><%= current_user.username %>'s public repository list</h1>

<h3>Repository count <%= @repos.count %></h3>
<% @repos.each do |repo| %>
  <%= link_to repo[:name], repo[:html_url] %><br><br>
<% end %>